
version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file sam-template.yaml --s3-bucket rdpacheco-aws-cf-artifacts \
        --output-template-file packaged-template.yaml
artifacts:
  type: zip
  files:
    - packaged-template.yaml
